import { useEffect, useState } from "react";
import { createPortal } from "react-dom";
import { Save, UsersRound, X } from "lucide-react";
import GroupMembersModal from "./GroupMembersModal";

export default function GroupFormModal({ open, group, members, onClose, onSave, onTransfer }) {
  if(!open) return null;
  return createPortal(<Content key={group?.id||"new"} group={group} members={members} onClose={onClose} onSave={onSave} onTransfer={onTransfer}/>,document.body);
}
function Content({group,members,onClose,onSave,onTransfer}){
  const [form,setForm]=useState({name:group?.name||"",markup:group?.markup??0,status:group?.status||"active"});
  const [error,setError]=useState("");
  useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=old}},[]);
  const submit=e=>{e.preventDefault();if(!form.name.trim()){setError("اكتب اسم المجموعة.");return}onSave({...form,name:form.name.trim(),markup:Number(form.markup)||0})};
  return <div className="fixed inset-0 z-[130] flex items-end justify-center bg-slate-950/60 sm:items-center sm:p-4" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="flex max-h-[92dvh] w-full max-w-[600px] flex-col overflow-hidden rounded-t-[28px] bg-white sm:rounded-[28px] dark:bg-[#111827]"><header className="flex items-center gap-3 border-b border-slate-100 p-4 dark:border-white/10"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-violet-500/10 text-violet-600 dark:text-violet-300"><UsersRound className="h-5 w-5"/></span><div className="flex-1"><h2 className="text-base font-black text-slate-950 dark:text-white">{group?"تعديل المجموعة":"إضافة مجموعة"}</h2><p className="text-[9px] font-bold text-slate-400">إدارة النسبة والأعضاء المرتبطين</p></div><button onClick={onClose} type="button" className="grid h-9 w-9 place-items-center rounded-xl bg-slate-100 dark:bg-white/[0.06]"><X className="h-4 w-4"/></button></header><form onSubmit={submit} className="overflow-y-auto p-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="اسم المجموعة"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className={input}/></Field><Field label="نسبة الإضافة %"><input type="number" min="0" step="0.01" value={form.markup} onChange={e=>setForm({...form,markup:e.target.value})} className={input}/></Field></div><Field label="حالة المجموعة" className="mt-3"><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className={input}><option value="active">نشطة</option><option value="inactive">غير نشطة</option></select></Field>{group&&<GroupMembersModal members={members} onTransfer={onTransfer}/>} {error&&<p className="mt-3 rounded-xl bg-rose-50 p-2 text-[9px] font-black text-rose-700 dark:bg-rose-500/10 dark:text-rose-300">{error}</p>}</form><footer className="sticky bottom-0 grid grid-cols-2 gap-2 border-t border-slate-100 bg-white p-3 dark:border-white/10 dark:bg-[#111827]"><button type="button" onClick={onClose} className="h-11 rounded-2xl border border-slate-200 text-xs font-black dark:border-white/10 dark:text-white">إلغاء</button><button type="button" onClick={submit} className="inline-flex h-11 items-center justify-center gap-2 rounded-2xl bg-gradient-to-l from-violet-600 to-blue-500 text-xs font-black text-white"><Save className="h-4 w-4"/>حفظ التعديل</button></footer></section></div>;
}
function Field({label,className="",children}){return <label className={`block ${className}`}><span className="mb-1 block text-[9px] font-black text-slate-500 dark:text-slate-300">{label}</span>{children}</label>}
const input="h-11 w-full rounded-2xl border border-slate-200 bg-slate-50 px-3 text-xs font-black outline-none focus:border-violet-400 dark:border-white/10 dark:bg-[#0B1220] dark:text-white";
