import { useEffect, useMemo, useState } from "react";
import { BadgeDollarSign, CheckCircle2, Clock3, HandCoins, Mail, UsersRound, XCircle } from "lucide-react";
import { agentEarningsSeed, subAgentRequestsSeed, subAgentRequestStorageKey } from "../../data/adminExtended";
import { userGroups, userGroupRates } from "../../data/adminUsers";
import { useToast } from "../../components/ToastProvider";
import { SkeletonBlock } from "../../components/Skeletons";
import EmptyState from "../../components/EmptyState";

function getInitialRequests() {
  try {
    const stored = JSON.parse(localStorage.getItem(subAgentRequestStorageKey) || "null");
    return stored && !subAgentRequestsSeed.some((item) => item.id === stored.id) ? [stored, ...subAgentRequestsSeed] : subAgentRequestsSeed;
  } catch { return subAgentRequestsSeed; }
}

export default function AdminSubAgentsPage() {
  const [tab, setTab] = useState("earnings");
  const [requests, setRequests] = useState(getInitialRequests);
  const [loading, setLoading] = useState(true);
  const [accepting, setAccepting] = useState(null);
  const { showToast } = useToast();
  useEffect(() => { const timer = setTimeout(() => setLoading(false), 520); return () => clearTimeout(timer); }, []);
  const totalEarnings = agentEarningsSeed.reduce((sum, item) => sum + item.earning, 0);
  const agents = new Set(agentEarningsSeed.map((item) => item.agent)).size;
  const updateRequest = (id, patch) => { setRequests((current) => current.map((item) => item.id === id ? { ...item, ...patch } : item)); try { const stored = JSON.parse(localStorage.getItem(subAgentRequestStorageKey) || "null"); if (stored?.id === id) localStorage.setItem(subAgentRequestStorageKey, JSON.stringify({ ...stored, ...patch })); } catch { /* UI state remains available. */ } };
  return <div dir="rtl" className="space-y-4"><Header /><div className="grid grid-cols-2 gap-2.5 lg:grid-cols-4"><Stat icon={UsersRound} label="الوكلاء المحققون للربح" value={agents} /><Stat icon={HandCoins} label="المدعوون" value={agentEarningsSeed.length} /><Stat icon={BadgeDollarSign} label="إجمالي الأرباح" value={`$${totalEarnings.toFixed(2)}`} /><Stat icon={Clock3} label="طلبات معلقة" value={requests.filter((item) => item.status === "pending").length} /></div><div className="grid grid-cols-2 rounded-2xl bg-slate-100 p-1 dark:bg-white/[0.06]"><button onClick={() => setTab("earnings")} className={`h-10 rounded-xl text-[10px] font-black ${tab === "earnings" ? "bg-white text-violet-700 shadow-sm dark:bg-[#111827] dark:text-violet-300" : "text-slate-500"}`}>الأرباح والإحالات</button><button onClick={() => setTab("requests")} className={`h-10 rounded-xl text-[10px] font-black ${tab === "requests" ? "bg-white text-violet-700 shadow-sm dark:bg-[#111827] dark:text-violet-300" : "text-slate-500"}`}>طلبات وكيل فرعي</button></div>{loading ? <div className="grid gap-3 sm:grid-cols-2">{Array.from({ length: 4 }).map((_, index) => <SkeletonBlock key={index} className="h-44 rounded-[22px]" />)}</div> : tab === "earnings" ? <Earnings /> : <Requests requests={requests} onAccept={setAccepting} onReject={(request) => { updateRequest(request.id, { status: "rejected" }); showToast({ type: "warning", title: "تم رفض طلب الوكيل", message: request.name }); }} />}<AcceptModal request={accepting} onClose={() => setAccepting(null)} onAccept={(group, rate) => { updateRequest(accepting.id, { status: "approved", newGroup: group, newRate: rate, invitedBy: null }); showToast({ type: "success", title: "تم قبول طلب الوكيل الفرعي", message: `${accepting.name} أصبح ضمن مجموعة ${group} بنسبة ${rate}%، وتم إلغاء الإحالة السابقة وإرسال إشعار للمستخدم.` }); setAccepting(null); }} /></div>;
}
function Header() { return <section className="flex items-center gap-3 rounded-[26px] border border-violet-200 bg-gradient-to-l from-white to-violet-50 p-5 dark:border-white/10 dark:bg-[linear-gradient(135deg,#111827,#17152A)]"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-blue-500 text-white"><HandCoins className="h-5 w-5" /></span><div><h1 className="text-2xl font-black dark:text-white">طلبات وكيل فرعي وأرباحهم</h1><p className="text-[9px] font-bold text-slate-400">مراجعة طلبات التجار وتتبع أرباح الإحالات</p></div></section>; }
function Stat({ icon: Icon, label, value }) { return <article className="rounded-[20px] border border-slate-200 bg-white p-3 dark:border-white/10 dark:bg-[#111827]"><Icon className="h-8 w-8 rounded-xl bg-violet-500/10 p-2 text-violet-600" /><b dir={String(value).startsWith("$") ? "ltr" : undefined} className="mt-2 block text-right text-xl dark:text-white">{typeof value === "number" ? value.toLocaleString("ar-EG") : value}</b><p className="text-[8px] font-black text-slate-400">{label}</p></article>; }
function Earnings() { const byAgent = useMemo(() => Object.groupBy ? Object.groupBy(agentEarningsSeed, (item) => item.agent) : agentEarningsSeed.reduce((all, item) => ({ ...all, [item.agent]: [...(all[item.agent] || []), item] }), {}), []); return <div className="grid gap-3 lg:grid-cols-2">{Object.entries(byAgent).map(([agent, rows]) => <article key={agent} className="rounded-[23px] border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-[#111827]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-violet-500/10 font-black text-violet-600">{agent.slice(0, 1)}</span><div className="flex-1"><h2 className="text-sm font-black dark:text-white">{agent}</h2><p className="text-[8px] text-slate-400">دعا {rows.length} أشخاص</p></div><b dir="ltr" className="text-emerald-600">${rows.reduce((sum, row) => sum + row.earning, 0).toFixed(2)}</b></div><div className="mt-3 space-y-2">{rows.map((row) => <div key={row.id} className="flex items-center gap-2 rounded-xl bg-slate-50 p-2.5 dark:bg-[#0B1220]"><div className="min-w-0 flex-1"><b className="block truncate text-[9px] dark:text-white">{row.invited}</b><small className="text-[7px] text-slate-400">{row.orders} طلب · مبيعات ${row.revenue}</small></div><span dir="ltr" className="text-[9px] font-black text-emerald-600">+${row.earning.toFixed(2)}</span></div>)}</div></article>)}</div>; }
function Requests({ requests, onAccept, onReject }) { return requests.length ? <div className="grid gap-3 sm:grid-cols-2">{requests.map((request) => <article key={request.id} className="rounded-[23px] border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-[#111827]"><div className="flex items-start gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-sky-500/10 font-black text-sky-600">{request.name.slice(0, 1)}</span><div className="min-w-0 flex-1"><h2 className="truncate text-sm font-black dark:text-white">{request.name}</h2><p dir="ltr" className="truncate text-right text-[8px] text-slate-400">{request.email}</p></div><RequestBadge status={request.status} /></div><p className="mt-3 rounded-xl bg-slate-50 p-3 text-[9px] font-bold leading-5 text-slate-600 dark:bg-[#0B1220] dark:text-slate-300">{request.message}</p><div className="mt-2 grid grid-cols-2 gap-2 text-[8px] font-black text-slate-500"><p>المجموعة: {request.newGroup || request.currentGroup}</p><p>النسبة: {request.newRate ?? request.currentRate}%</p><p className="col-span-2">الدعوة الحالية: {request.invitedBy || "تم إلغاؤها"}</p></div>{request.status === "pending" && <div className="mt-3 grid grid-cols-2 gap-2"><button onClick={() => onReject(request)} className="h-10 rounded-xl bg-rose-500/10 text-[9px] font-black text-rose-700 dark:text-rose-300">رفض</button><button onClick={() => onAccept(request)} className="h-10 rounded-xl bg-emerald-600 text-[9px] font-black text-white">قبول وتحديد المجموعة</button></div>}</article>)}</div> : <EmptyState title="لا توجد طلبات وكيل فرعي" />; }
function RequestBadge({ status }) { const meta = { pending: ["قيد الانتظار", "bg-orange-500/10 text-orange-700"], approved: ["مقبول", "bg-emerald-500/10 text-emerald-700"], rejected: ["مرفوض", "bg-rose-500/10 text-rose-700"] }[status]; return <span className={`rounded-full px-2 py-1 text-[8px] font-black ${meta[1]}`}>{meta[0]}</span>; }
function AcceptModal({ request, onClose, onAccept }) { const [group, setGroup] = useState("Reseller"); const rate = userGroupRates[group] ?? 0; useEffect(() => { setGroup("Reseller"); }, [request]); if (!request) return null; return <div className="fixed inset-0 z-[140] grid place-items-center bg-slate-950/65 p-4"><section className="w-full max-w-[460px] rounded-[26px] bg-white p-4 dark:bg-[#111827]"><div className="flex items-center gap-3"><CheckCircle2 className="h-5 w-5 text-emerald-500" /><div className="flex-1"><h2 className="text-sm font-black dark:text-white">قبول طلب الوكيل</h2><p className="text-[8px] text-slate-400">{request.name}</p></div><button onClick={onClose}><XCircle className="h-4 w-4" /></button></div><label className="mt-4 block"><span className="text-[8px] font-black text-slate-400">المجموعة الجديدة ونسبتها</span><select value={group} onChange={(event) => setGroup(event.target.value)} className="mt-1 h-11 w-full rounded-2xl bg-slate-50 px-3 text-[10px] font-black dark:bg-[#0B1220] dark:text-white">{userGroups.filter((item) => item !== "Admin").map((item) => <option key={item} value={item}>{item} — {userGroupRates[item] ?? 0}%</option>)}</select></label><div className="mt-3 flex items-center justify-between rounded-2xl border border-violet-200 bg-violet-50 p-3 dark:border-violet-400/20 dark:bg-violet-500/10"><span><span className="block text-[8px] font-black text-violet-500">المجموعة المختارة</span><strong className="mt-1 block text-xs text-violet-800 dark:text-violet-200">{group}</strong></span><span className="text-right"><span className="block text-[8px] font-black text-violet-500">نسبة المجموعة</span><strong dir="ltr" className="mt-1 block text-xl text-violet-700 dark:text-violet-300">{rate}%</strong></span></div><p className="mt-3 rounded-xl bg-orange-50 p-2.5 text-[8px] font-bold leading-5 text-orange-700 dark:bg-orange-500/10 dark:text-orange-300">عند القبول ستُلغى دعوة {request.invitedBy || "المستخدم السابق"}، وتصبح أرباح المستخدم من خلال حسابه كوكيل فقط.</p><button onClick={() => onAccept(group, rate)} className="mt-3 h-11 w-full rounded-2xl bg-emerald-600 text-[10px] font-black text-white">تأكيد القبول وإرسال الإشعار</button></section></div>; }
