import { useEffect, useMemo, useState } from "react";
import { Coins, LockKeyhole, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { currencyCatalog } from "../../data/adminExtended";
import { useToast } from "../../components/ToastProvider";
import { SkeletonBlock } from "../../components/Skeletons";
import EmptyState from "../../components/EmptyState";
import ConfirmDialog from "../../components/admin/products/ConfirmDialog";

export default function AdminCurrenciesPage() {
  const [favorites, setFavorites] = useState(currencyCatalog.filter((item) => ["USD", "EGP", "SAR", "AED"].includes(item.code)));
  const [catalogQuery, setCatalogQuery] = useState("");
  const [favoriteQuery, setFavoriteQuery] = useState("");
  const [catalogOpen, setCatalogOpen] = useState(false);
  const [editing, setEditing] = useState(null);
  const [deleting, setDeleting] = useState(null);
  const [loading, setLoading] = useState(true);
  const { showToast } = useToast();
  useEffect(() => { const timer = setTimeout(() => setLoading(false), 500); return () => clearTimeout(timer); }, []);
  const catalogResults = useMemo(() => currencyCatalog.filter((item) => `${item.name} ${item.code}`.toLowerCase().includes(catalogQuery.toLowerCase())), [catalogQuery]);
  const favoriteResults = favorites.filter((item) => `${item.name} ${item.code}`.toLowerCase().includes(favoriteQuery.toLowerCase()));
  const save = (currency, rate) => { setFavorites((current) => current.some((item) => item.code === currency.code) ? current.map((item) => item.code === currency.code ? { ...item, rate: Number(rate) } : item) : [...current, { ...currency, rate: Number(rate) }]); showToast({ type: "success", title: editing ? "تم تعديل سعر الصرف" : "تمت إضافة العملة", message: `${currency.name} · ${rate} مقابل الدولار` }); setEditing(null); setCatalogOpen(false); };
  return <div dir="rtl" className="space-y-4"><Header onCatalog={() => setCatalogOpen(true)} /><section className="rounded-[23px] border border-slate-200 bg-white p-4 dark:border-white/10 dark:bg-[#111827]"><h2 className="text-sm font-black dark:text-white">كتالوج العملات</h2><p className="mt-1 text-[9px] font-bold text-slate-400">ابحث في أشهر العملات العالمية ثم اختر العملة لإضافتها.</p><label className="relative mt-3 block"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-violet-500" /><input value={catalogQuery} onChange={(event) => setCatalogQuery(event.target.value)} onFocus={() => setCatalogOpen(true)} placeholder="ابحث عن عملة بالاسم أو الرمز" className="h-11 w-full rounded-2xl bg-slate-50 pe-9 ps-3 text-[10px] font-black dark:bg-[#0B1220] dark:text-white" /></label></section><section><div className="mb-3"><h2 className="text-base font-black dark:text-white">العملات المفضلة</h2><label className="relative mt-2 block"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={favoriteQuery} onChange={(event) => setFavoriteQuery(event.target.value)} placeholder="بحث في العملات المفضلة" className="h-10 w-full rounded-xl border border-slate-200 bg-white pe-9 ps-3 text-[9px] font-black dark:border-white/10 dark:bg-[#111827] dark:text-white" /></label></div>{loading ? <div className="grid grid-cols-2 gap-3 lg:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <SkeletonBlock key={index} className="h-40 rounded-[22px]" />)}</div> : favoriteResults.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{favoriteResults.map((currency) => <CurrencyCard key={currency.code} currency={currency} onEdit={() => setEditing(currency)} onDelete={() => setDeleting(currency)} />)}</div> : <EmptyState icon={Coins} title="لا توجد عملات مطابقة" />}</section><CatalogModal open={catalogOpen} query={catalogQuery} onQuery={setCatalogQuery} results={catalogResults} favorites={favorites} onClose={() => setCatalogOpen(false)} onChoose={(currency) => setEditing(currency)} /><RateModal currency={editing} exists={favorites.some((item) => item.code === editing?.code)} onClose={() => setEditing(null)} onSave={save} /><ConfirmDialog open={Boolean(deleting)} title="حذف العملة؟" message={`سيتم حذف ${deleting?.name || ""} من العملات المفضلة.`} onCancel={() => setDeleting(null)} onConfirm={() => { setFavorites((current) => current.filter((item) => item.code !== deleting.code)); showToast({ type: "success", title: "تم حذف العملة" }); setDeleting(null); }} /></div>;
}
function Header({ onCatalog }) { return <section className="flex items-center gap-3 rounded-[26px] border border-violet-200 bg-gradient-to-l from-white to-violet-50 p-5 dark:border-white/10 dark:bg-[linear-gradient(135deg,#111827,#17152A)]"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-blue-500 text-white"><Coins className="h-5 w-5" /></span><div className="min-w-0 flex-1"><h1 className="text-2xl font-black dark:text-white">إدارة العملات</h1><p className="text-[9px] font-bold text-slate-400">أسعار الصرف مقابل الدولار الأمريكي</p></div><button onClick={onCatalog} className="inline-flex h-10 items-center gap-1 rounded-xl bg-violet-600 px-3 text-[9px] font-black text-white"><Plus className="h-4 w-4" />إضافة عملة</button></section>; }
function CurrencyCard({ currency, onEdit, onDelete }) { const fixed = currency.code === "USD"; return <article className="rounded-[22px] border border-slate-200 bg-white p-4 shadow-[0_12px_30px_rgba(15,23,42,0.05)] dark:border-white/10 dark:bg-[#111827]"><div className="flex items-center gap-3"><span className="text-3xl">{currency.flag}</span><div className="min-w-0 flex-1"><h3 className="truncate text-sm font-black dark:text-white">{currency.name}</h3><p dir="ltr" className="text-right text-[9px] font-black text-violet-600">{currency.code} · {currency.symbol}</p></div>{fixed && <span className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1 text-[7px] font-black text-slate-500 dark:bg-white/[0.06]"><LockKeyhole className="h-2.5 w-2.5" />ثابت</span>}</div><div className="mt-3 rounded-2xl bg-violet-50 p-3 dark:bg-violet-500/[0.08]"><p className="text-[8px] font-black text-violet-500">سعر الصرف مقابل 1 USD</p><strong dir="ltr" className="mt-1 block text-right text-xl text-violet-700 dark:text-violet-300">{currency.rate.toLocaleString("en-US", { maximumFractionDigits: 4 })} {currency.code}</strong></div>{!fixed && <div className="mt-3 grid grid-cols-2 gap-2"><button onClick={onEdit} className="inline-flex h-9 items-center justify-center gap-1 rounded-xl bg-sky-500/10 text-[8px] font-black text-sky-700 dark:text-sky-300"><Pencil className="h-3.5 w-3.5" />تعديل</button><button onClick={onDelete} className="inline-flex h-9 items-center justify-center gap-1 rounded-xl bg-rose-500/10 text-[8px] font-black text-rose-700 dark:text-rose-300"><Trash2 className="h-3.5 w-3.5" />حذف</button></div>}</article>; }
function CatalogModal({ open, query, onQuery, results, favorites, onClose, onChoose }) { if (!open) return null; const added = new Set(favorites.map((item) => item.code)); return <div className="fixed inset-0 z-[130] flex items-end justify-center bg-slate-950/60 sm:items-center sm:p-4"><section className="flex max-h-[90dvh] w-full max-w-[680px] flex-col rounded-t-[28px] bg-white sm:rounded-[28px] dark:bg-[#111827]"><header className="flex items-center gap-3 border-b p-4 dark:border-white/10"><Coins className="h-5 w-5 text-violet-500" /><h2 className="flex-1 text-sm font-black dark:text-white">كتالوج العملات العالمية</h2><button onClick={onClose}><X className="h-4 w-4" /></button></header><div className="p-4"><input value={query} onChange={(event) => onQuery(event.target.value)} placeholder="بحث في الكتالوج" className="h-10 w-full rounded-xl bg-slate-50 px-3 text-[9px] font-black dark:bg-[#0B1220] dark:text-white" /></div><div className="grid gap-2 overflow-y-auto px-4 pb-4 sm:grid-cols-2">{results.map((currency) => <button key={currency.code} disabled={added.has(currency.code)} onClick={() => onChoose(currency)} className="flex items-center gap-3 rounded-2xl border border-slate-100 p-3 text-right disabled:opacity-45 dark:border-white/10"><span className="text-2xl">{currency.flag}</span><span className="min-w-0 flex-1"><b className="block truncate text-[10px] dark:text-white">{currency.name}</b><small dir="ltr" className="text-[8px] text-violet-500">{currency.code} · {currency.symbol}</small></span><span className="text-[8px] font-black text-slate-400">{added.has(currency.code) ? "مضافة" : "إضافة"}</span></button>)}</div></section></div>; }
function RateModal({ currency, exists, onClose, onSave }) { const [rate, setRate] = useState(currency?.rate || 1); useEffect(() => setRate(currency?.rate || 1), [currency]); if (!currency) return null; return <div className="fixed inset-0 z-[150] grid place-items-center bg-slate-950/65 p-4"><section className="w-full max-w-[420px] rounded-[26px] bg-white p-4 dark:bg-[#111827]"><div className="flex items-center gap-3"><span className="text-3xl">{currency.flag}</span><div className="flex-1"><h2 className="text-sm font-black dark:text-white">{exists ? "تعديل سعر الصرف" : "إضافة العملة"}</h2><p className="text-[8px] text-slate-400">{currency.name} · {currency.code}</p></div><button onClick={onClose}><X className="h-4 w-4" /></button></div><label className="mt-4 block"><span className="text-[9px] font-black text-slate-500">سعر العملة مقابل 1 دولار</span><input type="number" min="0" step="0.0001" value={rate} onChange={(event) => setRate(event.target.value)} className="mt-1 h-11 w-full rounded-2xl bg-slate-50 px-3 text-xs font-black dark:bg-[#0B1220] dark:text-white" /></label><button onClick={() => onSave(currency, rate)} className="mt-4 h-11 w-full rounded-2xl bg-violet-600 text-[10px] font-black text-white">{exists ? "حفظ التعديل" : "إضافة العملة"}</button></section></div>; }
